-- Run this once in Supabase SQL Editor.
create table if not exists public.sponsors (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.sponsors enable row level security;

drop policy if exists "Public can read sponsors" on public.sponsors;
create policy "Public can read sponsors"
on public.sponsors
for select
to anon, authenticated
using (true);

drop policy if exists "Admin can insert sponsors" on public.sponsors;
create policy "Admin can insert sponsors"
on public.sponsors
for insert
to authenticated
with check (auth.uid() = '89a2fd68-393b-45df-8220-431dca902d3d'::uuid);

drop policy if exists "Admin can update sponsors" on public.sponsors;
create policy "Admin can update sponsors"
on public.sponsors
for update
to authenticated
using (auth.uid() = '89a2fd68-393b-45df-8220-431dca902d3d'::uuid)
with check (auth.uid() = '89a2fd68-393b-45df-8220-431dca902d3d'::uuid);

drop policy if exists "Admin can delete sponsors" on public.sponsors;
create policy "Admin can delete sponsors"
on public.sponsors
for delete
to authenticated
using (auth.uid() = '89a2fd68-393b-45df-8220-431dca902d3d'::uuid);
